name: LaserWorkflow
on: [pull_request, push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: 
          java-version: 1.8
      - run: build.sh
      - run: test.sh
      - run: clean.sh
